package com.example.ogrimorio.database.initial_inserts

const val INITIAL_CRITICAL = """
        INSERT INTO Criticals (name, effect, type_id, category_id) VALUES 
('Tendão rompido', 'A iniciativa do alvo se torna 0, a partir do proximo turno', 1, 1),
('Coxa furada', 'A iniciativa do alvo se torna 0, a partir do proximo turno', 1, 2),
('Pancada no joelho', 'A iniciativa do alvo se torna 0, a partir do proximo turno', 1, 3),
('Medo arcano', 'A iniciativa do alvo se torna 0, a partir do proximo turno', 1, 5),
('Flecha no pé', 'A iniciativa do alvo se torna 0, a partir do proximo turno', 1, 4),
('Derrame ocular', 'Constituiçaõ CD 15, o alvo fica cego até tratamento', 1, 3),
('Punhalada', 'constituição CD 15, se falhar, você da um ADO no alvo', 1, 3),
('Touche', 'constituição CD 15, se falhar, você da um ADO no alvo', 1, 2),
('Giro de lâmina', 'constituição CD 15, se falhar, você da um ADO no alvo', 1, 1),
('Figado perfurado', 'Durante o proximo descanso longo, o alvo recupera apenas metade dos pontos de vida. Caso seja um NPC, rerrole', 1, 2),
('Sobrevida arcana', 'Ganhe pontos de vida temporarios igual ao dobro do seu nivel ou nivel de desafio (min 2)', 1, 5),
('Senhor do tempo(surto de turno)', 'ganhe um turno extra', 1, 5),
('Empolgado', 'Ganhe uma ação bonus extra neste turno', 1, 3),
('Empolgado', 'Ganhe uma ação bonus extra neste turno', 1, 1),
('Empolgado', 'Ganhe uma ação bonus extra neste turno', 1, 2),
('Empolgado', 'Ganhe uma ação bonus extra neste turno', 1, 4),
('Porrada no joelho', 'Movimento diminuído 5 feet até tratamento', 1, 3),
('Corte na coxa', 'Movimento diminuído 5 feet até tratamento', 1, 1),
('Magia Ecoa III', 'Não gaste Slot com a magia lançada, se não usar slot, rerrole', 1, 5),
('Vórtex temporal', 'o alvo desaparece. no início de seu próximo turno, ele reaparece no local desocupado mais próximo de onde ele estava', 1, 5),
('Pulso mágico', 'O alvo é empurrado 10 feet para trás, e fica caído', 1, 5),
('Miolo solto', 'O alvo esquece aleatoriamente um idioma, até receber tratamento. se NPC rerrole', 1, 3),
('Beijando o chão ', 'o alvo fica caído ', 1, 3),
('Pregado no lugar', 'o alvo fica Impedido, até passar no teste CD 15 atletismo ', 1, 2),
('Sensibilidade mágica', 'O Alvo ganha vunerabilidade ao tipo de sua magia, até receber tratamento', 1, 5),
('Bagunça mental', 'o alvo não consegue distinguir seres vivos de mortos, até tratamento', 1, 3),
('Investida intimidadora', 'O alvo não consegue te atacar até o fim do seu proximo turno', 1, 3),
('Investida intimidadora', 'O alvo não consegue te atacar até o fim do seu proximo turno', 1, 1),
('Ferimento interno', 'O alvo não pode realizar ações bonus ou reações até realizar tratamento', 1, 2),
('Ferimento interno', 'O alvo não pode realizar ações bonus ou reações até realizar tratamento', 1, 3),
('Ferimento interno', 'O alvo não pode realizar ações bonus ou reações até realizar tratamento', 1, 4),
('Debi e loide', 'o alvo não pode se concentrar até o fim do seu próximo turno', 1, 3),
('Descontrole', 'A magia é direcionada a um aliado aleatorio', 2, 5),
('Nervo pinçado', 'O alvo nunca pode receber vantagem, até receber tratamento', 1, 2),
('Perna quebrada', 'O alvo perde 10 feet do movimento pra sempre', 1, 3),
('olho por olho', 'o alvo só pode atacar você, até te dar a mesma quantidade de dano que você acabou de dar nele.', 1, 1),
('olho por olho', 'o alvo só pode atacar você, até te dar a mesma quantidade de dano que você acabou de dar nele.', 1, 2),
('olho por olho', 'o alvo só pode atacar você, até te dar a mesma quantidade de dano que você acabou de dar nele.', 1, 3),
('olho por olho', 'o alvo só pode atacar você, até te dar a mesma quantidade de dano que você acabou de dar nele.', 1, 5),
('olho por olho', 'o alvo só pode atacar você, até te dar a mesma quantidade de dano que você acabou de dar nele.', 1, 4),
('Corte doloroso', 'O alvo só pode usar sua ação, ou se mover, nunca os dois. Até receber tratamento', 1, 1),
('Magia de sangue', 'O alvo sofre 1 ponto de dano, para cada 2 pontos de dano que você se der agora', 1, 5),
('Rosto retalhado', 'O alvo sofre -3 de penalidade em testes de persuasão e +3 de bonus em intimidação, até tratamento. Se NPC rerrole', 1, 1),
('Cravada nas costas', 'O alvo sofre penalidade de -3 em força e destreza, até o proximo turno', 1, 2),
('Vertigem', 'O alvo tem 50% de chance de errar seus ataques, até receber tratamento ', 1, 3),
('Ferida aberta', 'O hp maximo é reduzido no valor do dano, até receber tratamento', 1, 1),
('Explosão precoce', 'A magia explode em suas mãos, role o dano normalmente e tome metade', 2, 5),
('Calor da batalha', 'O proximo ataque d20 que tirar 11 ou mais, é tratado como acerto critico', 1, 1),
('Magia Ecoa II', 'Repita a magia gratuitamente(ação e slot) no mesmo turno', 1, 5),
('Magia ecoa I', 'Repita a magia gratuitamente(ação e slot) no proximo turno', 1, 5),
('Guarda aberta', 'Ataques contra você tem vantagem até o inicio do seu proximo turno', 2, 3),
('Guarda aberta', 'Ataques contra você tem vantagem até o inicio do seu proximo turno', 2, 2),
('Guarda aberta', 'Ataques contra você tem vantagem até o inicio do seu proximo turno', 2, 1),
('Guarda aberta', 'Ataques contra você tem vantagem até o inicio do seu proximo turno', 2, 4),
('Segunda chance', 'Jogue um D20, 13+ nada acontece, 12- Rolê 2 erros críticos', 2, 1),
('Preso na lâmina', 'Se o alvo for de tamanho igual ou menos a você, ele fica agarrado', 1, 1),
('Descarga Cerebral', 'Seu alinhamento muda para o contrário, do bem para o mal, vice versa. Se neutro, faça aleatoriamente ', 1, 5),
('Segunda chance', 'Jogue um D20, 13+ nada acontece, 12- Rolê 2 erros críticos', 2, 2),
('Magia ampliada', 'Sua magia é castada com 1 nivel superior', 1, 5),
('Fraqueza temporaria', 'Todo dano do alvo é reduzido pela metade, até o fim do seu proximo turno', 1, 2),
('Fraqueza temporaria', 'Todo dano do alvo é reduzido pela metade, até o fim do seu proximo turno', 1, 1),
('Fraqueza temporaria', 'Todo dano do alvo é reduzido pela metade, até o fim do seu proximo turno', 1, 3),
('Fraqueza temporaria', 'Todo dano do alvo é reduzido pela metade, até o fim do seu proximo turno', 1, 5),
('Fraqueza temporaria', 'Todo dano do alvo é reduzido pela metade, até o fim do seu proximo turno', 1, 4),
('Enxaqueca', 'Todos os ataques do alvo são em desvantagem, até tratamento', 1, 3),
('Golpe amplo', 'um alvo adjacente recebe dano igual a metade do dano', 1, 2),
('Cheiro de sangue', 'Uma criatura que você pode ver recebe inspiração', 1, 1),
('Aura de proteção ', 'Você ganha +2 de CA até o fim do próximo turno', 1, 5),
('Corte limpo', 'Você ganha inspiração', 1, 1),
('Magia vampirica', 'você ganha metade do dano em pontos de vida', 1, 5),
('Resistencia física', 'Você ganha resistencia a dano cortante, perfurante e concussão, até o fim do seu proximo turno', 1, 5),
('Resistência mágica', 'Você ganha resistencia a dano magico até o fim do seu proximo turno', 1, 5),
('Sede de sangue', 'Você pode fazer um ataque em desvantagem, ou mover seu deslocamento total', 1, 3),
('Sede de sangue', 'Você pode fazer um ataque em desvantagem, ou mover seu deslocamento total', 1, 2),
('Sede de sangue', 'Você pode fazer um ataque em desvantagem, ou mover seu deslocamento total', 1, 1),
('Telepata', 'Você pode se comunicar telepaticamente até o descanso longo, se NPC rerrole', 1, 5),
('Dobra Planar', 'Você pode se teletransportar a uma distância igual a seu deslocamento', 1, 5),
('Antecipação', 'Você pode usar sua ação bonus para usar a ação preparar', 1, 2),
('Olhos rápidos', 'Você pode usar a ação Dodge gratuitamente este turno', 1, 1),
('Olhos rápidos', 'Você pode usar a ação Dodge gratuitamente este turno', 1, 3),
('Olhos rápidos', 'Você pode usar a ação Dodge gratuitamente este turno', 1, 2),
('Acabei aqui', 'Você pode usar a ação Desingage gratuitamente este turno', 1, 1),
('Acabei aqui', 'Você pode usar a ação Desingage gratuitamente este turno', 1, 3),
('Acabei aqui', 'Você pode usar a ação Desingage gratuitamente este turno', 1, 2),
('Carrasco', 'Se o dano matar o alvo, ganhe mais um ataque, com vantagem e +1 dado de dano.', 1, 3),
('Carrasco', 'Se o dano matar o alvo, ganhe mais um ataque, com vantagem e +1 dado de dano.', 1, 2),
('Carrasco', 'Se o dano matar o alvo, ganhe mais um ataque, com vantagem e +1 dado de dano.', 1, 1),
('Assustado', 'O alvo não tem reação até o fim de seu proximo turno', 1, 1),
('Assustado', 'O alvo não tem reação até o fim de seu proximo turno', 1, 2),
('Assustado', 'O alvo não tem reação até o fim de seu proximo turno', 1, 3),
('Assustado', 'O alvo não tem reação até o fim de seu proximo turno', 1, 5),
('Assustado', 'O alvo não tem reação até o fim de seu proximo turno', 1, 4),
('Segunda chance', 'Jogue um D20, 13+ nada acontece, 12- Rolê 2 erros críticos', 2, 3),
('Segunda chance', 'Jogue um D20, 13+ nada acontece, 12- Rolê 2 erros críticos', 2, 5),
('Headshot', 'Dobre o dano total', 1, 4),
('Bambeou', 'CD 15 Constituição, o alvo fica caído', 1, 3),
('Bambeou', 'CD 15 Constituição, o alvo fica caído', 1, 1),
('Bambeou', 'CD 15 Constituição, o alvo fica caído', 1, 2),
('Bambeou', 'CD 15 Constituição, o alvo fica caído', 1, 4),
('Ponto exposto', 'A CA é reduzida em 1 até reparar armadura, pode acumular', 1, 3),
('Ponto exposto', 'A CA é reduzida em 1 até reparar armadura, pode acumular', 1, 1),
('Ponto exposto', 'A CA é reduzida em 1 até reparar armadura, pode acumular', 1, 2),
('Ponto exposto', 'A CA é reduzida em 1 até reparar armadura, pode acumular', 1, 4),
('Criar abertura', 'O próximo a atacar este alvo ganha vantagem', 1, 3),
('Criar abertura', 'O próximo a atacar este alvo ganha vantagem', 1, 1),
('Criar abertura', 'O próximo a atacar este alvo ganha vantagem', 1, 2),
('Criar abertura', 'O próximo a atacar este alvo ganha vantagem', 1, 4),
('Segunda chance', 'Jogue um D20, 13+ nada acontece, 12- Rolê 2 erros críticos', 2, 4),
('Debi e Loide', 'o alvo não pode se concentrar até o fim do seu próximo turno', 2, 5),
('Perdido', 'O proximo ataque d20 que tirar 10 ou menos, é tratado como erro critico', 2, 2),
('Perdido', 'O proximo ataque d20 que tirar 10 ou menos, é tratado como erro critico', 2, 1),
('Perdido', 'O proximo ataque d20 que tirar 10 ou menos, é tratado como erro critico', 2, 3),
('Perdido', 'O proximo ataque d20 que tirar 10 ou menos, é tratado como erro critico', 2, 4),
('Avariado', 'Perca -1 em seu modificador de ataque', 2, 4),
('Avariado', 'Perca -1 em seu modificador de ataque', 2, 1),
('Avariado', 'Perca -1 em seu modificador de ataque', 2, 2),
('Avariado', 'Perca -1 em seu modificador de ataque', 2, 3),
('Fogo amigo', 'Role dano normalmente contra o aliado mais próximo do alvo', 2, 4),
('Fogo amigo', 'Role dano normalmente contra o aliado mais próximo do alvo, se não tiver ninguem rerrole', 2, 2),
('Fogo amigo', 'Role dano normalmente contra o aliado mais próximo do alvo, se não tiver ninguem rerrole', 2, 3),
('Fogo amigo', 'Role dano normalmente contra o aliado mais próximo do alvo, se não tiver ninguem rerrole', 2, 1),
('Ops errei', 'Sorteie qualquer outra magia preparada e lance imediatamente gastando somente o slot já utilizado. se a magia sorteada for de toque, você gasta na pessoa mais próxima, se não tiver, use em você. Este uso deve priorizar ajudar seus oponentes.', 2, 5),
('Droga!', 'Sua arma cai atras do alvo', 2, 3),
('Droga!', 'Sua arma cai atras do alvo', 2, 2),
('Droga!', 'Sua arma cai atras do alvo', 2, 1),
('Corte profundo', 'Dano extra igual ao seu nível, ou CR (min 1)', 1, 1),
('Estocada profunda', 'Dano extra igual ao seu nível, ou CR (min 1)', 1, 2),
('Paulada', 'Dano extra igual ao seu nível, ou CR (min 1)', 1, 3),
('No alvo', 'Dano extra igual ao seu nível, ou CR (min 1)', 1, 4),
('Desarmado!', 'A arma do alvo fica caída atrás de você', 1, 1),
('Desarmado!', 'A arma do alvo fica caída atrás de você', 1, 2),
('Desarmado!', 'A arma do alvo fica caída atrás de você', 1, 3),
('Grito de guerra!', 'Ganha +1 em seu modificador de ataque', 1, 4),
('Grito de guerra!', 'Ganha +1 em seu modificador de ataque', 1, 1),
('Grito de guerra!', 'Ganha +1 em seu modificador de ataque', 1, 2),
('Grito de guerra!', 'Ganha +1 em seu modificador de ataque', 1, 3),
('Escorregou', 'Você fica caído', 2, 3),
('Escorregou', 'Você fica caído', 2, 2),
('Escorregou', 'Você fica caído', 2, 1),
('Escorregou', 'Você fica caído', 2, 4),
('A magia pune', 'Você é teletransportado para o local mais próximo do alvo', 2, 5),
('Pulso torcido', 'Suas jogadas de ataque perdem o bonus de proficiencia até o fim do combate', 2, 1),
('Pulso torcido', 'Suas jogadas de ataque perdem o bonus de proficiencia até o fim do combate', 2, 3),
('Pulso torcido', 'Suas jogadas de ataque perdem o bonus de proficiencia até o fim do combate', 2, 2),
('Energia drenada', 'Role 1d20, se tirar 5 ou menos, perca um slote de magia de seu nivel mais alto, caso contrario, perca um slot de magia de seu nivel mais baixo', 2, 5),
('Pé torcido', 'Seu deslocamento cai pela metade até o fim do encontro', 2, 1),
('Pé torcido', 'Seu deslocamento cai pela metade até o fim do encontro', 2, 3),
('Pé torcido', 'Seu deslocamento cai pela metade até o fim do encontro', 2, 2),
('Onda de verdades', 'Você só pode falar a verdade até receber tratamento, e não consegue deixar uma pergunta sem resposta', 2, 5),
('Braço quebrado', 'Você só pode usar uma das mãos, até receber tratamento', 2, 1),
('Braço quebrado', 'Você só pode usar uma das mãos, até receber tratamento', 2, 3),
('Braço quebrado', 'Você só pode usar uma das mãos, até receber tratamento', 2, 2),
('Onda de medo', 'Sua próxima ação não pode ser um ataque', 2, 4),
('Onda de medo', 'Sua próxima ação não pode ser um ataque', 2, 1),
('Onda de medo', 'Sua próxima ação não pode ser um ataque', 2, 3),
('Onda de medo', 'Sua próxima ação não pode ser um ataque', 2, 2),
('Ego ferido', 'Você não pode atacar outro alvo, até que este esteja morto ou derrotado', 2, 4),
('Ego ferido', 'Você não pode atacar outro alvo, até que este esteja morto ou derrotado', 2, 1),
('Ego ferido', 'Você não pode atacar outro alvo, até que este esteja morto ou derrotado', 2, 3),
('Ego ferido', 'Você não pode atacar outro alvo, até que este esteja morto ou derrotado', 2, 2),
('A magia move', 'Um aliado aleatório e teleportado para o lado do alvo', 2, 5),
('Transferencia de poder', 'O próximo ataque do alvo é tratado como um acerto crítico', 2, 5),
('Pertubaçã mágica', 'Você adquire Cenosilicafobia, e passa a ter medo paralisante e irracional de copos vazios (Principalmente de bebidas alcólidas', 2, 5),
('Ataque de Risada Nervosa', 'Ao errar, você começa a rir incontrolavelmente. Precisa passar em um teste de Constituição (CD 12) ou ficará rindo por 1 turno, incapaz de agir.', 2, 5),
('Vitimismo', 'Você vira um poço de sentimentos negativos até o descanso longo', 2, 5),
('Vitimismo', 'Você vira um poço de sentimentos negativos até o descanso longo', 2, 1),
('Vitimismo', 'Você vira um poço de sentimentos negativos até o descanso longo', 2, 2),
('Vitimismo', 'Você vira um poço de sentimentos negativos até o descanso longo', 2, 3),
('Vitimismo', 'Você vira um poço de sentimentos negativos até o descanso longo', 2, 4),
('Dor nas costas', 'Você não consegue realizar um descanso curto até receber tratamento', 2, 1),
('Dor nas costas', 'Você não consegue realizar um descanso curto até receber tratamento', 2, 2),
('Dor nas costas', 'Você não consegue realizar um descanso curto até receber tratamento', 2, 3),
('Dor nas costas', 'Você não consegue realizar um descanso curto até receber tratamento', 2, 4),
('Reforço mágico', 'O alvo fica imune a qualquer condição até o fim do encontro', 2, 5),
('Tadala de 20', 'O alvo tem seu tamanho aumentado como na magia aumentar, até o fim do encontro', 2, 5),
('Tão pequeno', 'Você tem seu tamanho reduzido como na magia diminuir, até o fim do encontro', 2, 5),
('Tão pequeno', 'O aliado mais próximo do alvo tem seu tamanho reduzido até o fim do encontro', 2, 5),
('Tadala de 20', 'Role 1d6 e use o efeito da magia aumentar em: 1 - Em você 2 - 5 - No aliado mais próximo do alvo 6 - Um aliado a sua escolha', 1, 5),
('Costela quebrada', 'Você recebe 1 ponto de dano, para cada ação, ação bonus ou reação que fizer, até receber tratamento', 2, 1),
('Costela quebrada', 'Você recebe 1 ponto de dano, para cada ação, ação bonus ou reação que fizer, até receber tratamento', 2, 2),
('Costela quebrada', 'Você recebe 1 ponto de dano, para cada ação, ação bonus ou reação que fizer, até receber tratamento', 2, 3),
('Inimigo marcial', 'Você troca de lugar com o alvo, e fica caído', 2, 1),
('Inimigo marcial', 'Você troca de lugar com o alvo, e fica caído', 2, 2),
('Inimigo marcial', 'Você troca de lugar com o alvo, e fica caído', 2, 3),
('Erro de julgamento', 'O alvo não é mais uma ameaça para você, até ele te dar algum dano', 2, 1),
('Erro de julgamento', 'O alvo não é mais uma ameaça para você, até ele te dar algum dano', 2, 2),
('Erro de julgamento', 'O alvo não é mais uma ameaça para você, até ele te dar algum dano', 2, 3),
('Erro de julgamento', 'O alvo não é mais uma ameaça para você, até ele te dar algum dano', 2, 4),
('Que coisa feia', 'Você fica amendrotado pelo alvo até o fim do seu proximo turno', 2, 1),
('Que coisa feia', 'Você fica amendrotado pelo alvo até o fim do seu proximo turno', 2, 2),
('Que coisa feia', 'Você fica amendrotado pelo alvo até o fim do seu proximo turno', 2, 3),
('Sai pra la!', 'Você é empurrado 10 feet para trás, se passar por alguem, fica caído. Se bater em alguma estrutura tome 1d6 dano.', 2, 1),
('Sai pra la!', 'Você é empurrado 10 feet para trás, se passar por alguem, fica caído. Se bater em alguma estrutura tome 1d6 dano.', 2, 2),
('Sai pra la!', 'Você é empurrado 10 feet para trás, se passar por alguem, fica caído. Se bater em alguma estrutura tome 1d6 dano.', 2, 3),
('Enterrada', 'Sua arma está presa no chão! É necessária uma ação bonus e um teste CD 15 atletismo para retira-la de la', 2, 1),
('Enterrada', 'Sua arma está presa no chão! É necessária uma ação bonus e um teste CD 15 atletismo para retira-la de la', 2, 2),
('Enterrada', 'Sua arma está presa no chão! É necessária uma ação bonus e um teste CD 15 atletismo para retira-la de la', 2, 3),
('Foi mal ai', 'Você desarma um aliado aleatório proximo ao alvo, a arma cai 10 feet longe de seu dono', 2, 4),
('Mordeu a lingua', 'Você morde sua lingua e não consegue falar até receber tratamento. (gemidos são permitidos)', 2, 1),
('Mordeu a lingua', 'Você morde sua lingua e não consegue falar até receber tratamento. (gemidos são permitidos)', 2, 2),
('Mordeu a lingua', 'Você morde sua lingua e não consegue falar até receber tratamento. (gemidos são permitidos)', 2, 3),
('Mordeu a lingua', 'Você morde sua lingua e não consegue falar até receber tratamento. (gemidos são permitidos)', 2, 4),
('A magia ensina', 'O alvo aprende a conjurar está magia, apenas uma vez, sem necessidade de componentes ou foco mágico, até o fim do encontro', 2, 5),
('Efeito dominó', 'Você e todos ao seu redor, exceto o alvo, ficam caídos', 2, 1),
('Efeito dominó', 'Você e todos ao seu redor, exceto o alvo, ficam caídos', 2, 2),
('Efeito dominó', 'Você e todos ao seu redor, exceto o alvo, ficam caídos', 2, 3);
        """