package com.example.ogrimorio.database.initial_inserts

const val INITIAL_CRITICAL = """
        INSERT INTO Criticals (name, effect, type_id, category_id) VALUES 
('Tendão rompido', 'A iniciativa do alvo se torna 0, a partir do próximo turno', 1, 1),
('Coxa furada', 'A iniciativa do alvo se torna 0, a partir do próximo turno', 1, 2),
('Pancada no joelho', 'A iniciativa do alvo se torna 0, a partir do próximo turno', 1, 3),
('Medo arcano', 'A iniciativa do alvo se torna 0, a partir do próximo turno', 1, 5),
('Flecha no pé', 'A iniciativa do alvo se torna 0, a partir do próximo turno', 1, 4),
('Derrame ocular', 'Constituição CD 15, o alvo fica cego até tratamento', 1, 3),
('Punhalada', 'Constituição CD 15, se falhar, você dá um AdO no alvo', 1, 3),
('Touché', 'Constituição CD 15, se falhar, você dá um AdO no alvo', 1, 2),
('Giro de lâmina', 'Constituição CD 15, se falhar, você dá um AdO no alvo', 1, 1),
('Fígado perfurado', 'Durante o próximo descanso longo, o alvo recupera apenas metade dos pontos de vida. Caso seja um NPC, rerrole', 1, 2),
('Sobrevida arcana', 'Ganhe pontos de vida temporários iguais ao dobro do seu nível ou Nível de Desafio (mín. 2)', 1, 5),
('Senhor do Tempo (Surto de Turno)', 'Ganhe um turno extra', 1, 5),
('Empolgado', 'Ganhe uma ação bônus extra neste turno', 1, 3),
('Empolgado', 'Ganhe uma ação bônus extra neste turno', 1, 1),
('Empolgado', 'Ganhe uma ação bônus extra neste turno', 1, 2),
('Empolgado', 'Ganhe uma ação bônus extra neste turno', 1, 4),
('Porrada no joelho', 'Movimento diminuído em 5 pés até tratamento', 1, 3),
('Corte na coxa', 'Movimento diminuído em 5 pés até tratamento', 1, 1),
('Magia Ecoa III', 'Não gaste slot com a magia lançada; se não usar slot, rerrole', 1, 5),
('Vórtex temporal', 'O alvo desaparece. No início de seu próximo turno, ele reaparece no local desocupado mais próximo de onde ele estava', 1, 5),
('Pulso mágico', 'O alvo é empurrado 10 pés para trás e fica caído', 1, 5),
('Miolo solto', 'O alvo esquece aleatoriamente um idioma até receber tratamento. Se NPC, rerrole', 1, 3),
('Beijando o chão', 'O alvo fica caído', 1, 3),
('Pregado no lugar', 'O alvo fica Impedido até passar no teste CD 15 de Atletismo', 1, 2),
('Sensibilidade mágica', 'O alvo ganha vulnerabilidade ao tipo de sua magia até receber tratamento', 1, 5),
('Bagunça mental', 'O alvo não consegue distinguir seres vivos de mortos até tratamento', 1, 3),
('Investida intimidadora', 'O alvo não consegue te atacar até o fim do seu próximo turno', 1, 3),
('Investida intimidadora', 'O alvo não consegue te atacar até o fim do seu próximo turno', 1, 1),
('Ferimento interno', 'O alvo não pode realizar ações bônus ou reações até realizar tratamento', 1, 2),
('Ferimento interno', 'O alvo não pode realizar ações bônus ou reações até realizar tratamento', 1, 3),
('Ferimento interno', 'O alvo não pode realizar ações bônus ou reações até realizar tratamento', 1, 4),
('Debi e Loide', 'O alvo não pode se concentrar até o fim do seu próximo turno', 1, 3),
('Descontrole', 'A magia é direcionada a um aliado aleatório', 2, 5),
('Nervo pinçado', 'O alvo nunca pode receber vantagem até receber tratamento', 1, 2),
('Perna quebrada', 'O alvo perde 10 pés de movimento para sempre', 1, 3),
('Olho por Olho', 'O alvo só pode atacar você, até te dar a mesma quantidade de dano que você acabou de dar nele.', 1, 1),
('Olho por Olho', 'O alvo só pode atacar você, até te dar a mesma quantidade de dano que você acabou de dar nele.', 1, 2),
('Olho por Olho', 'O alvo só pode atacar você, até te dar a mesma quantidade de dano que você acabou de dar nele.', 1, 3),
('Olho por Olho', 'O alvo só pode atacar você, até te dar a mesma quantidade de dano que você acabou de dar nele.', 1, 5),
('Olho por Olho', 'O alvo só pode atacar você, até te dar a mesma quantidade de dano que você acabou de dar nele.', 1, 4),
('Corte doloroso', 'O alvo só pode usar sua ação ou se mover, nunca os dois, até receber tratamento', 1, 1),
('Magia de sangue', 'O alvo sofre 1 ponto de dano para cada 2 pontos de dano que você causar a si mesmo agora', 1, 5),
('Rosto retalhado', 'O alvo sofre -3 de penalidade em testes de Persuasão e +3 de bônus em Intimidação até tratamento. Se NPC, rerrole', 1, 1),
('Cravada nas costas', 'O alvo sofre penalidade de -3 em Força e Destreza até o próximo turno', 1, 2),
('Vertigem', 'O alvo tem 50% de chance de errar seus ataques até receber tratamento', 1, 3),
('Ferida aberta', 'O PV máximo é reduzido no valor do dano até receber tratamento', 1, 1),
('Explosão precoce', 'A magia explode em suas mãos, role o dano normalmente e tome metade', 2, 5),
('Calor da batalha', 'O próximo ataque d20 que tirar 11 ou mais é tratado como acerto crítico', 1, 1),
('Magia Ecoa II', 'Repita a magia gratuitamente (ação e slot) no mesmo turno', 1, 5),
('Magia Ecoa I', 'Repita a magia gratuitamente (ação e slot) no próximo turno', 1, 5),
('Guarda aberta', 'Ataques contra você têm vantagem até o início do seu próximo turno', 2, 3),
('Guarda aberta', 'Ataques contra você têm vantagem até o início do seu próximo turno', 2, 2),
('Guarda aberta', 'Ataques contra você têm vantagem até o início do seu próximo turno', 2, 1),
('Guarda aberta', 'Ataques contra você têm vantagem até o início do seu próximo turno', 2, 4),
('Segunda chance', 'Jogue um d20: 13+ nada acontece; 12 ou menos role 2 erros críticos', 2, 1),
('Preso na lâmina', 'Se o alvo for de tamanho igual ou menor que você, ele fica agarrado', 1, 1),
('Descarga Cerebral', 'Seu alinhamento muda para o contrário (do bem para o mal e vice-versa). Se neutro, faça aleatoriamente', 1, 5),
('Segunda chance', 'Jogue um d20: 13+ nada acontece; 12 ou menos role 2 erros críticos', 2, 2),
('Magia ampliada', 'Sua magia é conjurada com 1 nível superior', 1, 5),
('Fraqueza temporária', 'Todo dano do alvo é reduzido pela metade até o fim do seu próximo turno', 1, 2),
('Fraqueza temporária', 'Todo dano do alvo é reduzido pela metade até o fim do seu próximo turno', 1, 1),
('Fraqueza temporária', 'Todo dano do alvo é reduzido pela metade até o fim do seu próximo turno', 1, 3),
('Fraqueza temporária', 'Todo dano do alvo é reduzido pela metade até o fim do seu próximo turno', 1, 5),
('Fraqueza temporária', 'Todo dano do alvo é reduzido pela metade até o fim do seu próximo turno', 1, 4),
('Enxaqueca', 'Todos os ataques do alvo são com desvantagem até tratamento', 1, 3),
('Golpe amplo', 'Um alvo adjacente recebe dano igual a metade do dano', 1, 2),
('Cheiro de sangue', 'Uma criatura que você pode ver recebe inspiração', 1, 1),
('Aura de proteção', 'Você ganha +2 de CA até o fim do próximo turno', 1, 5),
('Corte limpo', 'Você ganha inspiração', 1, 1),
('Magia Vampírica', 'Você ganha metade do dano em pontos de vida', 1, 5),
('Resistência física', 'Você ganha resistência a dano cortante, perfurante e concussão até o fim do seu próximo turno', 1, 5),
('Resistência mágica', 'Você ganha resistência a dano mágico até o fim do seu próximo turno', 1, 5),
('Sede de sangue', 'Você pode fazer um ataque com desvantagem ou mover seu deslocamento total', 1, 3),
('Sede de sangue', 'Você pode fazer um ataque com desvantagem ou mover seu deslocamento total', 1, 2),
('Sede de sangue', 'Você pode fazer um ataque com desvantagem ou mover seu deslocamento total', 1, 1),
('Telepata', 'Você pode se comunicar telepaticamente até o descanso longo. Se NPC, rerrole', 1, 5),
('Dobra Planar', 'Você pode se teletransportar a uma distância igual a seu deslocamento', 1, 5),
('Antecipação', 'Você pode usar sua ação bônus para usar a ação Preparar', 1, 2),
('Olhos rápidos', 'Você pode usar a ação Esquivar gratuitamente este turno', 1, 1),
('Olhos rápidos', 'Você pode usar a ação Esquivar gratuitamente este turno', 1, 3),
('Olhos rápidos', 'Você pode usar a ação Esquivar gratuitamente este turno', 1, 2),
('Acabei aqui', 'Você pode usar a ação Desengajar gratuitamente este turno', 1, 1),
('Acabei aqui', 'Você pode usar a ação Desengajar gratuitamente este turno', 1, 3),
('Acabei aqui', 'Você pode usar a ação Desengajar gratuitamente este turno', 1, 2),
('Carrasco', 'Se o dano matar o alvo, ganhe mais um ataque com vantagem e +1 dado de dano', 1, 3),
('Carrasco', 'Se o dano matar o alvo, ganhe mais um ataque com vantagem e +1 dado de dano', 1, 2),
('Carrasco', 'Se o dano matar o alvo, ganhe mais um ataque com vantagem e +1 dado de dano', 1, 1),
('Assustado', 'O alvo não tem reação até o fim de seu próximo turno', 1, 1),
('Assustado', 'O alvo não tem reação até o fim de seu próximo turno', 1, 2),
('Assustado', 'O alvo não tem reação até o fim de seu próximo turno', 1, 3),
('Assustado', 'O alvo não tem reação até o fim de seu próximo turno', 1, 5),
('Assustado', 'O alvo não tem reação até o fim de seu próximo turno', 1, 4),
('Segunda chance', 'Jogue um d20: 13+ nada acontece; 12 ou menos role 2 erros críticos', 2, 3),
('Segunda chance', 'Jogue um d20: 13+ nada acontece; 12 ou menos role 2 erros críticos', 2, 5),
('Headshot', 'Dobre o dano total', 1, 4),
('Bambeou', 'CD 15 Constituição, o alvo fica caído', 1, 3),
('Bambeou', 'CD 15 Constituição, o alvo fica caído', 1, 1),
('Bambeou', 'CD 15 Constituição, o alvo fica caído', 1, 2),
('Bambeou', 'CD 15 Constituição, o alvo fica caído', 1, 4),
('Ponto exposto', 'A CA é reduzida em 1 até reparar armadura, pode acumular', 1, 3),
('Ponto exposto', 'A CA é reduzida em 1 até reparar armadura, pode acumular', 1, 1),
('Ponto exposto', 'A CA é reduzida em 1 até reparar armadura, pode acumular', 1, 2),
('Ponto exposto', 'A CA é reduzida em 1 até reparar armadura, pode acumular', 1, 4),
('Criar abertura', 'O próximo a atacar este alvo ganha vantagem', 1, 3),
('Criar abertura', 'O próximo a atacar este alvo ganha vantagem', 1, 1),
('Criar abertura', 'O próximo a atacar este alvo ganha vantagem', 1, 2),
('Criar abertura', 'O próximo a atacar este alvo ganha vantagem', 1, 4),
('Segunda chance', 'Jogue um d20: 13+ nada acontece; 12 ou menos role 2 erros críticos', 2, 4),
('Debi e Loide', 'O alvo não pode se concentrar até o fim do seu próximo turno', 2, 5),
('Perdido', 'O próximo ataque d20 que tirar 10 ou menos é tratado como erro crítico', 2, 2),
('Perdido', 'O próximo ataque d20 que tirar 10 ou menos é tratado como erro crítico', 2, 1),
('Perdido', 'O próximo ataque d20 que tirar 10 ou menos é tratado como erro crítico', 2, 3),
('Perdido', 'O próximo ataque d20 que tirar 10 ou menos é tratado como erro crítico', 2, 4),
('Avariado', 'Receba -1 em seu modificador de ataque', 2, 4),
('Avariado', 'Receba -1 em seu modificador de ataque', 2, 1),
('Avariado', 'Receba -1 em seu modificador de ataque', 2, 2),
('Avariado', 'Receba -1 em seu modificador de ataque', 2, 3),
('Fogo amigo', 'Role dano normalmente contra o aliado mais próximo do alvo', 2, 4),
('Fogo amigo', 'Role dano normalmente contra o aliado mais próximo do alvo; se não tiver ninguém, rerrole', 2, 2),
('Fogo amigo', 'Role dano normalmente contra o aliado mais próximo do alvo; se não tiver ninguém, rerrole', 2, 3),
('Fogo amigo', 'Role dano normalmente contra o aliado mais próximo do alvo; se não tiver ninguém, rerrole', 2, 1),
('Ops errei', 'Sorteie qualquer outra magia preparada e lance imediatamente gastando somente o slot já utilizado. Se a magia sorteada for de toque, você gasta na pessoa mais próxima; se não tiver, use em você. Este uso deve priorizar ajudar seus oponentes.', 2, 5),
('Droga!', 'Sua arma cai atrás do alvo', 2, 3),
('Droga!', 'Sua arma cai atrás do alvo', 2, 2),
('Droga!', 'Sua arma cai atrás do alvo', 2, 1),
('Corte profundo', 'Dano extra igual ao seu nível ou ND (mín. 1)', 1, 1),
('Estocada profunda', 'Dano extra igual ao seu nível ou ND (mín. 1)', 1, 2),
('Paulada', 'Dano extra igual ao seu nível ou ND (mín. 1)', 1, 3),
('No alvo', 'Dano extra igual ao seu nível ou ND (mín. 1)', 1, 4),
('Desarmado!', 'A arma do alvo fica caída atrás de você', 1, 1),
('Desarmado!', 'A arma do alvo fica caída atrás de você', 1, 2),
('Desarmado!', 'A arma do alvo fica caída atrás de você', 1, 3),
('Grito de guerra!', 'Ganha +1 em seu modificador de ataque', 1, 4),
('Grito de guerra!', 'Ganha +1 em seu modificador de ataque', 1, 1),
('Grito de guerra!', 'Ganha +1 em seu modificador de ataque', 1, 2),
('Grito de guerra!', 'Ganha +1 em seu modificador de ataque', 1, 3),
('Escorregou', 'Você fica caído', 2, 3),
('Escorregou', 'Você fica caído', 2, 2),
('Escorregou', 'Você fica caído', 2, 1),
('Escorregou', 'Você fica caído', 2, 4),
('A magia pune', 'Você é teletransportado para o local mais próximo do alvo', 2, 5),
('Pulso torcido', 'Suas jogadas de ataque perdem o bônus de proficiência até o fim do combate', 2, 1),
('Pulso torcido', 'Suas jogadas de ataque perdem o bônus de proficiência até o fim do combate', 2, 3),
('Pulso torcido', 'Suas jogadas de ataque perdem o bônus de proficiência até o fim do combate', 2, 2),
('Energia drenada', 'Role 1d20: se tirar 5 ou menos, perca um slot de magia de seu nível mais alto; caso contrário, perca um slot de magia de seu nível mais baixo', 2, 5),
('Pé torcido', 'Seu deslocamento cai pela metade até o fim do encontro', 2, 1),
('Pé torcido', 'Seu deslocamento cai pela metade até o fim do encontro', 2, 3),
('Pé torcido', 'Seu deslocamento cai pela metade até o fim do encontro', 2, 2),
('Onda de verdades', 'Você só pode falar a verdade até receber tratamento e não consegue deixar uma pergunta sem resposta', 2, 5),
('Braço quebrado', 'Você só pode usar uma das mãos até receber tratamento', 2, 1),
('Braço quebrado', 'Você só pode usar uma das mãos até receber tratamento', 2, 3),
('Braço quebrado', 'Você só pode usar uma das mãos até receber tratamento', 2, 2),
('Onda de medo', 'Sua próxima ação não pode ser um ataque', 2, 4),
('Onda de medo', 'Sua próxima ação não pode ser um ataque', 2, 1),
('Onda de medo', 'Sua próxima ação não pode ser um ataque', 2, 3),
('Onda de medo', 'Sua próxima ação não pode ser um ataque', 2, 2),
('Ego ferido', 'Você não pode atacar outro alvo até que este esteja morto ou derrotado', 2, 4),
('Ego ferido', 'Você não pode atacar outro alvo até que este esteja morto ou derrotado', 2, 1),
('Ego ferido', 'Você não pode atacar outro alvo até que este esteja morto ou derrotado', 2, 3),
('Ego ferido', 'Você não pode atacar outro alvo até que este esteja morto ou derrotado', 2, 2),
('A magia move', 'Um aliado aleatório é teletransportado para o lado do alvo', 2, 5),
('Transferência de poder', 'O próximo ataque do alvo é tratado como um acerto crítico', 2, 5),
('Perturbação mágica', 'Você adquire Cenosilicafobia e passa a ter medo paralisante e irracional de copos vazios (principalmente de bebidas alcoólicas)', 2, 5),
('Ataque de Risada Nervosa', 'Ao errar, você começa a rir incontrolavelmente. Precisa passar em um teste de Constituição (CD 12) ou ficará rindo por 1 turno, incapaz de agir.', 2, 5),
('Vitimismo', 'Você vira um poço de sentimentos negativos até o descanso longo', 2, 5),
('Vitimismo', 'Você vira um poço de sentimentos negativos até o descanso longo', 2, 1),
('Vitimismo', 'Você vira um poço de sentimentos negativos até o descanso longo', 2, 2),
('Vitimismo', 'Você vira um poço de sentimentos negativos até o descanso longo', 2, 3),
('Vitimismo', 'Você vira um poço de sentimentos negativos até o descanso longo', 2, 4),
('Dor nas costas', 'Você não consegue realizar um descanso curto até receber tratamento', 2, 1),
('Dor nas costas', 'Você não consegue realizar um descanso curto até receber tratamento', 2, 2),
('Dor nas costas', 'Você não consegue realizar um descanso curto até receber tratamento', 2, 3),
('Dor nas costas', 'Você não consegue realizar um descanso curto até receber tratamento', 2, 4),
('Reforço mágico', 'O alvo fica imune a qualquer condição até o fim do encontro', 2, 5),
('Tadala de 20', 'O alvo tem seu tamanho aumentado como na magia Aumentar/Reduzir, até o fim do encontro', 2, 5),
('Tão pequeno', 'Você tem seu tamanho reduzido como na magia Aumentar/Reduzir, até o fim do encontro', 2, 5),
('Tão pequeno', 'O aliado mais próximo do alvo tem seu tamanho reduzido até o fim do encontro', 2, 5),
('Tadala de 20', 'Role 1d6 e use o efeito da magia Aumentar em: 1 - Em você; 2 a 5 - No aliado mais próximo do alvo; 6 - Um aliado à sua escolha', 1, 5),
('Costela quebrada', 'Você recebe 1 ponto de dano para cada ação, ação bônus ou reação que fizer, até receber tratamento', 2, 1),
('Costela quebrada', 'Você recebe 1 ponto de dano para cada ação, ação bônus ou reação que fizer, até receber tratamento', 2, 2),
('Costela quebrada', 'Você recebe 1 ponto de dano para cada ação, ação bônus ou reação que fizer, até receber tratamento', 2, 3),
('Inimigo marcial', 'Você troca de lugar com o alvo e fica caído', 2, 1),
('Inimigo marcial', 'Você troca de lugar com o alvo e fica caído', 2, 2),
('Inimigo marcial', 'Você troca de lugar com o alvo e fica caído', 2, 3),
('Erro de julgamento', 'O alvo não é mais uma ameaça para você até ele te dar algum dano', 2, 1),
('Erro de julgamento', 'O alvo não é mais uma ameaça para você até ele te dar algum dano', 2, 2),
('Erro de julgamento', 'O alvo não é mais uma ameaça para você até ele te dar algum dano', 2, 3),
('Erro de julgamento', 'O alvo não é mais uma ameaça para você até ele te dar algum dano', 2, 4),
('Que coisa feia', 'Você fica amedrontado pelo alvo até o fim do seu próximo turno', 2, 1),
('Que coisa feia', 'Você fica amedrontado pelo alvo até o fim do seu próximo turno', 2, 2),
('Que coisa feia', 'Você fica amedrontado pelo alvo até o fim do seu próximo turno', 2, 3),
('Sai pra lá!', 'Você é empurrado 10 pés para trás; se passar por alguém, fica caído. Se bater em alguma estrutura, tome 1d6 de dano.', 2, 1),
('Sai pra lá!', 'Você é empurrado 10 pés para trás; se passar por alguém, fica caído. Se bater em alguma estrutura, tome 1d6 de dano.', 2, 2),
('Sai pra lá!', 'Você é empurrado 10 pés para trás; se passar por alguém, fica caído. Se bater em alguma estrutura, tome 1d6 de dano.', 2, 3),
('Enterrada', 'Sua arma está presa no chão! É necessária uma ação bônus e um teste CD 15 de Atletismo para retirá-la de lá', 2, 1),
('Enterrada', 'Sua arma está presa no chão! É necessária uma ação bônus e um teste CD 15 de Atletismo para retirá-la de lá', 2, 2),
('Enterrada', 'Sua arma está presa no chão! É necessária uma ação bônus e um teste CD 15 de Atletismo para retirá-la de lá', 2, 3),
('Foi mal aí', 'Você desarma um aliado aleatório próximo ao alvo; a arma cai a 10 pés de distância de seu dono', 2, 4),
('Mordeu a língua', 'Você morde sua língua e não consegue falar até receber tratamento (gemidos são permitidos).', 2, 1),
('Mordeu a língua', 'Você morde sua língua e não consegue falar até receber tratamento (gemidos são permitidos).', 2, 2),
('Mordeu a língua', 'Você morde sua língua e não consegue falar até receber tratamento (gemidos são permitidos).', 2, 3),
('Mordeu a língua', 'Você morde sua língua e não consegue falar até receber tratamento (gemidos são permitidos).', 2, 4),
('A magia ensina', 'O alvo aprende a conjurar esta magia, apenas uma vez, sem necessidade de componentes ou foco mágico, até o fim do encontro', 2, 5),
('Efeito dominó', 'Você e todos ao seu redor, exceto o alvo, ficam caídos', 2, 1),
('Efeito dominó', 'Você e todos ao seu redor, exceto o alvo, ficam caídos', 2, 2),
('Efeito dominó', 'Você e todos ao seu redor, exceto o alvo, ficam caídos', 2, 3),
('Sangramento Arterial', 'O alvo recebe 1d4 de dano necrótico no início de cada turno dele, até receber cura mágica ou passar num teste de Medicina CD 10', 1, 1),
('Sangramento Arterial', 'O alvo recebe 1d4 de dano necrótico no início de cada turno dele, até receber cura mágica ou passar num teste de Medicina CD 10', 1, 2),
('Quebra-Escudos', 'Se o alvo estiver usando escudo, ele o derruba e o escudo é arremessado a 10 pés de distância. Se não, adicione 1d6 de concussão ao dano', 1, 3),
('Tiro de Mestre', 'O projétil atravessa o primeiro alvo e acerta uma segunda criatura logo atrás (se houver) com a mesma jogada de ataque', 1, 4),
('Curto-Circuito Mágico', 'O alvo perde um slot de magia de nível 1 (ou o mais baixo disponível). Se não tiver slots, toma 1d6 de dano psíquico extra', 1, 5),
('Grito Desmoralizante', 'Você ruge após o golpe. Todos os inimigos a 30 pés devem passar em Sabedoria CD 13 ou ficam amedrontados até o fim do próximo turno', 1, 3),
('Grito Desmoralizante', 'Você ruge após o golpe. Todos os inimigos a 30 pés devem passar em Sabedoria CD 13 ou ficam amedrontados até o fim do próximo turno', 1, 1),
('Sifão de Mana', 'Você recupera um slot de magia de nível 1', 1, 5),
('Impacto Sísmico', 'O chão treme com seu golpe. O alvo e todas as criaturas adjacentes a ele devem passar em Destreza CD 14 ou cairão', 1, 3),
('Lâmina Dançarina', 'Após o ataque, você pode se mover até metade do seu deslocamento sem provocar ataques de oportunidade', 1, 1),
('Lâmina Dançarina', 'Após o ataque, você pode se mover até metade do seu deslocamento sem provocar ataques de oportunidade', 1, 2),
('Flecha Guiada', 'Sua munição faz uma curva impossível. O alvo não recebe benefícios de cobertura para este ataque. Se o alvo não estiver em cobertura adicione 1d6 de dano perfurante', 1, 4),
('Espirro Arcano', 'Ao conjurar, você espirra. A magia falha e você fica silenciado (incapaz de falar) até o fim do seu próximo turno', 2, 5),
('Cãibra Fulminante', 'Uma dor aguda na panturrilha. Seu deslocamento torna-se 0 até você gastar uma ação para massagear o local', 2, 1),
('Cãibra Fulminante', 'Uma dor aguda na panturrilha. Seu deslocamento torna-se 0 até você gastar uma ação para massagear o local', 2, 2),
('Cãibra Fulminante', 'Uma dor aguda na panturrilha. Seu deslocamento torna-se 0 até você gastar uma ação para massagear o local', 2, 3),
('Traição da Empunhadura', 'O suor faz a arma girar na sua mão. Você ataca com desvantagem no próximo turno', 2, 1),
('Traição da Empunhadura', 'O suor faz a arma girar na sua mão. Você ataca com desvantagem no próximo turno', 2, 2),
('Traição da Empunhadura', 'O suor faz a arma girar na sua mão. Você ataca com desvantagem no próximo turno', 2, 3),
('Ricochete Azarado', 'O projétil bate numa pedra e volta, acertando você. Tome 1d4 de dano do tipo da arma', 2, 4),
('Visão Turva', 'Suor ou sangue escorre nos seus olhos. Você fica cego até limpar o rosto (ação bônus)', 2, 1),
('Visão Turva', 'Suor ou sangue escorre nos seus olhos. Você fica cego até limpar o rosto (ação bônus)', 2, 2),
('Visão Turva', 'Suor ou sangue escorre nos seus olhos. Você fica cego até limpar o rosto (ação bônus)', 2, 3),
('Visão Turva', 'Suor ou sangue escorre nos seus olhos. Você fica cego até limpar o rosto (ação bônus)', 2, 4),
('Sobrecarga Mental', 'A energia mágica estala em sua mente. Você esquece a magia que tentou lançar até realizar um descanso curto', 2, 5),
('Tropeço Tático', 'Você tropeça em seus próprios pés. O alvo ganha vantagem no próximo ataque contra você', 2, 1),
('Tropeço Tático', 'Você tropeça em seus próprios pés. O alvo ganha vantagem no próximo ataque contra você', 2, 2),
('Tropeço Tático', 'Você tropeça em seus próprios pés. O alvo ganha vantagem no próximo ataque contra você', 2, 3),
('Munição Defeituosa', 'A corda do arco arrebenta ou a arma emperra. Requer uma ação para consertar antes de usar novamente', 2, 4),
('Excesso de Confiança', 'Você tenta um floreio desnecessário e se desequilibra. Fica atordoado até o início do seu próximo turno', 2, 1),
('Excesso de Confiança', 'Você tenta um floreio desnecessário e se desequilibra. Fica atordoado até o início do seu próximo turno', 2, 2),
('Excesso de Confiança', 'Você tenta um floreio desnecessário e se desequilibra. Fica atordoado até o início do seu próximo turno', 2, 3),
('Ataque de Pânico', 'Ao errar, você acredita que o inimigo é invencível. Deve usar todo seu movimento para fugir dele na sua próxima chance', 2, 1),
('Ataque de Pânico', 'Ao errar, você acredita que o inimigo é invencível. Deve usar todo seu movimento para fugir dele na sua próxima chance', 2, 2),
('Ataque de Pânico', 'Ao errar, você acredita que o inimigo é invencível. Deve usar todo seu movimento para fugir dele na sua próxima chance', 2, 3),
('Ataque de Pânico', 'Ao errar, você acredita que o inimigo é invencível. Deve usar todo seu movimento para fugir dele na sua próxima chance', 2, 4),
('Ataque de Pânico', 'Ao errar, você acredita que o inimigo é invencível. Deve usar todo seu movimento para fugir dele na sua próxima chance', 2, 5),
('Explosão', 'Ao tentar conjurar sua magia, algo da errado e uma explosão acontece, o barulho te deixa temporariamente surdo. Até receber tratamento, sempre que for conjurar uma magia role 1d4, com 1 a magia falha', 2, 5),
('Quase cego', 'Um golpe extremamente próximo aos olhos, o alvo recebe o status Cego', 1, 1),
('Quase cego', 'Um golpe extremamente próximo aos olhos, o alvo recebe o status Cego', 1, 2),
('Quase cego', 'Um golpe extremamente próximo aos olhos, o alvo recebe o status Cego', 1, 3),
('Quase cego', 'Um golpe extremamente próximo aos olhos, o alvo recebe o status Cego', 1, 4),
        """